Miscellaneous small improvements
* README.rst: add a concrete example to clarify command line usage, most
notably.

* flo_check_homework/main.py: minor bugfix when processing an OSError
exception: the "filename" attribute may be None.

* MANIFEST.in: make sure the flo_check_homework/images/unused directory
is not included in release tarballs.

* flo-check-homework.fr.ts: update the French translation.